/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "*.php",
    "api/**/*.php",
    "financeiro/**/*.php",
    "gerenciamento/**/*.php",
    "includes/**/*.php",
    "precificacao/**/*.php",
    "roteiros/**/*.php",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'title-sm': ['Hanken Grotesk', 'sans-serif'],
        'data-tabular': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'data-tabular': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      spacing: {
        'container-padding': '32px',
        'card-gap': '16px',
        'base': '8px',
        'gutter': '24px',
        'section-margin': '48px',
      },
      colors: {
        primary: '#cabeff',
        'on-primary': '#31009a',
        'primary-container': '#947dff',
        'on-primary-container': '#2a0088',
        secondary: '#c7c5d4',
        'on-secondary': '#2f2f3b',
        'secondary-container': '#484855',
        'on-secondary-container': '#b9b7c6',
        tertiary: '#ffb780',
        'on-tertiary': '#4e2600',
        'tertiary-container': '#d7791f',
        'on-tertiary-container': '#442000',
        background: '#131316',
        'on-background': '#e4e1e6',
        surface: '#131316',
        'on-surface': '#e4e1e6',
        'surface-variant': '#353438',
        'on-surface-variant': '#c9c4d8',
        outline: '#938ea1',
        'outline-variant': '#484555',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        success: '#10b981',
        distinto: {
          ink: '#111111',
          paper: '#ffffff',
          line: '#ececec',
          muted: '#777777',
        }
      }
    },
  },
  plugins: [],
}
