<?php
$caminho = __DIR__ . '/../gerenciamento/contrato_gerar.php';
$conteudo = file_get_contents($caminho);

$substituicoes = [
    // Palavras e padrões comuns de mojibake
    'CLÃ USULA' => 'CLÁUSULA',
    'CLÃ  USULA' => 'CLÁUSULA',
    'CLÃ\x81USULA' => 'CLÁUSULA',
    'CLÃ…USULA' => 'CLÁUSULA',
    'CLÃšSULA' => 'CLÁUSULA',
    'PrestaÃ§Ã£o' => 'Prestação',
    'ServiÃ§o' => 'Serviço',
    'ServiÃ§os' => 'Serviços',
    'DescriÃ§Ã£o' => 'Descrição',
    'descriÃ§Ã£o' => 'descrição',
    'SignatÃ¡rio' => 'Signatário',
    'SignatÃ¡rios' => 'Signatários',
    'CobranÃ§a' => 'Cobrança',
    'CobranÃ§as' => 'Cobranças',
    'CondiÃ§Ã£o' => 'Condição',
    'CondiÃ§Ãµes' => 'Condições',
    'condiÃ§Ãµes' => 'condições',
    'InÃ­cio' => 'Início',
    'EmissÃ£o' => 'Emissão',
    'BancÃ¡rio' => 'Bancário',
    'bancÃ¡rio' => 'bancário',
    'CartÃ£o' => 'Cartão',
    'cartÃ£o' => 'cartão',
    'CrÃ©dito' => 'Crédito',
    'crÃ©dito' => 'crédito',
    'Ãšltimo' => 'Último',
    'Ãºltimo' => 'último',
    'Ã ' => 'à',
    'Ã€' => 'À',
    '1Âª' => '1ª',
    'Ãºteis' => 'úteis',
    'apÃ³s' => 'após',
    'seleÃ§Ã£o' => 'seleção',
    'realizaÃ§Ã£o' => 'realização',
    'duraÃ§Ã£o' => 'duração',
    'padrÃ£o' => 'padrão',
    'climÃ¡ticas' => 'climáticas',
    'elÃ©trica' => 'elétrica',
    'alheios' => 'alheios',
    'forÃ§a' => 'força',
    'mÃ­nimo' => 'mínimo',
    'NÂº' => 'Nº',
    'nÂº' => 'nº',
    'irrevoÃ¡vel' => 'irrevogável',
    'irrevogÃ¡vel' => 'irrevogável',
    'divulgaÃ§Ã£o' => 'divulgação',
    'mÃ­dias' => 'mídias',
    'perÃ­odo' => 'período',
    'exibiÃ§Ã£o' => 'exibição',
    'publicaÃ§Ã£o' => 'publicação',
    'especÃ­ficas' => 'específicas',
    'atÃ©' => 'até',
    'confianÃ§a' => 'confiança',
    'antecedÃªncia' => 'antecedência',
    'necessÃ¡ria' => 'necessária',
    'preparaÃ§Ã£o' => 'preparação',
    'telefÃ´nicos' => 'telefônicos',
    'Ã¢mbito' => 'âmbito',
    'alimentaÃ§Ã£o' => 'alimentação',
    'trÃ¢nsito' => 'trânsito',
    'vigÃªncia' => 'vigência',
    'portfÃ³lio' => 'portfólio',
    'peÃ§as' => 'peças',
    'rescisÃ£o' => 'rescisão',
    'prÃ©vio' => 'prévio',
    'divergÃªncia' => 'divergência',
    'VitÃ³ria' => 'Vitória',
    'Ãºnica' => 'única',
    'responsÃ¡vel' => 'responsável',
    'mÃªs' => 'mês',
    'correÃ§Ã£o' => 'correção',
    'monetÃ¡ria' => 'monetária',
    'resoluÃ§Ã£o' => 'resolução',
    'dÃºvidas' => 'dúvidas',
    'controvÃ©rsias' => 'controvérsias',
    'renÃºncia' => 'renúncia',
    
    // Mojibake de caracteres individuais isolados
    'Ã¡' => 'á',
    'Ã©' => 'é',
    'Ã­' => 'í',
    'Ã³' => 'ó',
    'Ãº' => 'ú',
    'Ã¢' => 'â',
    'Ãª' => 'ê',
    'Ã´' => 'ô',
    'Ã§' => 'ç',
    'Ã£' => 'ã',
    'Ãµ' => 'õ',
    'Ã‡' => 'Ç',
    'â€“' => '–',
    'â€”' => '—',
    'â€œ' => '“',
    'â€' => '”',
    'â€˜' => '‘',
    'â€™' => '’',
    'â€¦' => '…',
    'Âº' => 'º',
    'Âª' => 'ª',
    'Â°' => '°',
    'Â§' => '§',
];

// Corrigindo padrões como CLÃ USULA onde pode haver espaços de controle estranhos
$conteudo = preg_replace('/CLÃ\s+USULA/i', 'CLÁUSULA', $conteudo);
$conteudo = preg_replace('/CLÃ\s*USULA/i', 'CLÁUSULA', $conteudo);

$conteudo = strtr($conteudo, $substituicoes);

file_put_contents($caminho, $conteudo);
echo "Arquivo corrigido com sucesso!\n";
